version: '3'
services:

  rabbit:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ app management UI port
    environment:
      RABBITMQ_ERLANG_COOKIE: "my_secret_cookie"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"